In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

np.int64(8)

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
# Reset array
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_arr = arr[0:6]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [15]:
#Broadcasting array
slice_of_arr[:]=99

In [16]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy = arr.copy()

In [19]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy[:]=1

In [21]:
arr_copy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

2D ARRAY EXAMPLES

In [23]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [24]:
#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
#Getting value in first row first column
arr_2d[0][0]

np.int64(5)

In [26]:
#Getting first row 
arr_2d[0]

array([ 5, 10, 15])

In [27]:
arr_2d[1][1]

np.int64(25)

In [29]:
arr_2d[2][1]

np.int64(40)

In [30]:
#Alternatively use comma and single square brackets
arr_2d[2,1]

np.int64(40)

In [31]:
#SLICE IN 2D ARRAYS
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [36]:
#Grabbing sub-sections of array
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
arr_2d[1:3,:2]

array([[20, 25],
       [35, 40]])

In [66]:
arr = np.arange(1,11)

In [70]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
bool_arr = arr > 5

In [72]:
bool_arr 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Get only values from array where condition was true

In [73]:
arr[bool_arr ]

array([ 6,  7,  8,  9, 10])

In [68]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [74]:
arr[arr < 5]

array([1, 2, 3, 4])

In [77]:
arr_2d=np.arange(50).reshape(5,10)

In [87]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [83]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [85]:
arr_2d[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [89]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])