In [1]:
conda install numpy

Jupyter detected...
3 channel Terms of Service accepted
Channels:
 - defaults
Platform: win-64
Solving environment: done

## Package Plan ##

  environment location: C:\Users\NathaliaSungkoora\anaconda3

  added / updated specs:
    - numpy


The following packages will be UPDATED:

  ca-certificates                      2025.2.25-haa95532_0 --> 2025.7.15-haa95532_0 
  certifi                         2025.4.26-py313haa95532_0 --> 2025.8.3-py313haa95532_0 



Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.




==> WARNING: A newer version of conda exists. <==
    current version: 25.5.1
    latest version: 25.7.0

Please update conda by running

    $ conda update -n base -c defaults conda




In [2]:
import numpy as np

In [4]:
my_list = [1,2,3]

In [5]:
my_list

[1, 2, 3]

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Casting to an array = 2D Array

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

All even values (use step size)

In [15]:
np.arange(0, 11,2)

array([ 0,  2,  4,  6,  8, 10])

Generate arrays of zeros or ones

ZEROS

In [16]:
np.zeros(3)

array([0., 0., 0.])

Passing a tuple if dimenesions that you want

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Two rows with three columns

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

ONES

In [20]:
np.ones(3)

array([1., 1., 1.])

Three rows and four columns of ONES

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

LINSPACE

Start num=0, End num=5, number points=10 (returns 1D vector)

In [23]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

eye->Creates an identity matrix

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Numpy also has lots of ways to create random number arrays

In [26]:
np.random.rand(2)

array([0.32205896, 0.2754554 ])

In [27]:
np.random.rand(5,5)

array([[0.51417814, 0.29915722, 0.97041854, 0.19391659, 0.00538558],
       [0.68880931, 0.79066424, 0.1611819 , 0.88524993, 0.74140075],
       [0.09333633, 0.13901485, 0.26668815, 0.75836394, 0.82806412],
       [0.2477862 , 0.09150441, 0.13480467, 0.3908029 , 0.44795483],
       [0.84451453, 0.14047073, 0.12095524, 0.01744948, 0.51272957]])

In [28]:
np.random.randn(2)

array([1.03666409, 0.94474743])

In [29]:
np.random.randn(4,4)

array([[-0.23419716,  0.41258929,  0.70471822, -2.21799334],
       [-2.24547248,  0.68698293, -1.72593234,  1.19345527],
       [-0.65611079,  1.86525769, -0.27928478, -1.16456195],
       [ 1.28783136,  0.53230903, -0.87970758,  0.2472598 ]])

In [30]:
np.random.randint(1,100)

26

In [31]:
np.random.randint(1,100,10)

array([ 2, 98, 47, 57, 39, 75, 17, 92, 68, 76], dtype=int32)

Example of ARRAYS AND METHODS

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr = np.random.randint(0,50,10)

In [35]:
ranarr

array([11, 28, 37,  5, 35, 15, 32, 40, 40, 32], dtype=int32)

Reshape->Returns an array containing the same data with a new shape.

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

MAX and MIN Values

In [37]:
ranarr

array([11, 28, 37,  5, 35, 15, 32, 40, 40, 32], dtype=int32)

In [38]:
ranarr.max()

np.int32(40)

In [39]:
ranarr.min()

np.int32(5)

In [40]:
ranarr.argmin()

np.int64(3)

In [41]:
ranarr.argmax()

np.int64(7)

In [42]:
# Vector
#One Dimensional
arr.shape

(25,)

In [43]:
# Notice the two sets of brackets
arr = arr.reshape(5,5)

In [44]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
#Two Dimensional
arr.shape

(5, 5)

In [47]:
#Get datatype of array

In [48]:
arr.dtype

dtype('int64')